version: 6

networks:
  base:
    rpcs:
      - https://mainnet.base.org
      - https://base.drpc.org
      - https://base-rpc.publicnode.com
      - https://developer-access-mainnet.base.org
    chain-id: 8453
    network-id: 8453
    currency: ETH

subgraphs:
  base: https://api.goldsky.com/api/public/project_clv14x04y9kzi01saerx7bxpg/subgraphs/ob4-base/2026-02-05-c4ef/gn

metaboards:
  base: https://api.goldsky.com/api/public/project_clv14x04y9kzi01saerx7bxpg/subgraphs/metadata-base/2025-07-06-594f/gn

raindexes:
  base:
    address: 0xe522cB4a5fCb2eb31a52Ff41a4653d85A4fd7C9D
    network: base
    subgraph: base
    deployment-block: 41747644
    local-db-remote: raindex

rainlangs:
  base:
    address: 0x22508460712C350e914b49155982d3A92D923b10
    network: base

using-tokens-from:
  - https://tokens.coingecko.com/base/all.json
  - https://raw.githubusercontent.com/albionlabs/tokenlist/main/albion.tokenlist.json

local-db-remotes:
  raindex: https://raindex-bootstrap-db.lon1.digitaloceanspaces.com/local-db-manifests/1779881382550/manifest.yaml

local-db-sync:
  base:
    batch-size: 50
    max-concurrent-batches: 1
    retry-attempts: 3
    retry-delay-ms: 1000
    rate-limit-delay-ms: 5000
    finality-depth: 4
    bootstrap-block-threshold: 300
    sync-interval-ms: 5000
